[phases.setup]
nixPkgs = ['nodejs_18', 'nodePackages.npm']
aptPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['npm ci --only=production']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run preview -- --host 0.0.0.0 --port 4173' 