# 🚀 Configuración Nixpacks optimizada para SvelteKit
# Academia Vallenata Online - Solución definitiva

[variables]
NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmd = "npm install --force --legacy-peer-deps"

[phases.build]
cmd = "npm run build"

[start]
cmd = "node build" 