[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'node build/index.js'

[variables]
NODE_ENV = 'production'
HOST = '0.0.0.0'
PORT = '3000' 