
[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node build"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "true"