# 🚀 Configuración Nixpacks optimizada para SvelteKit + Easypanel
# Academia Vallenata Online

[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmd = 'npm ci --only=production=false'

[phases.build]
cmd = 'npm run build'

[start]
cmd = 'node build' 